name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CUSTOM_DOMAIN: www.quantfusiontech.com
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-rss-plugin
      - run: mkdocs gh-deploy --force
